### ISSUE TITLE
Content Security Policy stops content from being loaded from Contentful

### ISSUE THREAD

**Issue by GaProgMan** [zacbraddy/tabsandspaceswebsite#7]
### Description

The current CSP (Content Security Policy) stops connections being made to the contentful servers. This can be seen by browsing the live site with the developer tools open. Several messages indicating that the CSP is blocking requests to `https://images.ctfassets.net` can be seen.

### Proposed Solution

Add `https://*.ctfassets.net` as an allowed `connect-src` directive within the CSP rule found in the firebase.json file. This will add `ctfassets.net` and all of it's sub-domains to the list of allowed URLs that the browser is allowed to connect to when accessing resources for the page.

**Comment by zacbraddy** [comment]
@GaProgMan merged your PR and I can't see errors in the console, I assume this is fixed? Reopen if you find that it isn't.
